name: Node.js Package

on:
    push:
        branches:
            - main

jobs:
<<<<<<< HEAD
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm install
            - run: npm publish
            - name: Release
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
=======
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm publish
      - name: Release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
>>>>>>> 2d06536816cf0d76652d41a890fc942d2f0f1f89

              run: npx semantic-release