name: Node.js Package

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org
            - run: npm publish
            - name: Release
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
